name: Publish releases to PyPI

on:
  release:
    types: [published, prereleased]

jobs:
  build-and-publish:
    name: Builds and publishes releases to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install wheel
        run: >-
          pip install wheel
      - name: Build
        run: >-
          python3 setup.py sdist bdist_wheel
      - name: Publish release to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
